# Generated by Django 5.1.5 on 2025-01-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_company_calloutcome_companycomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_target',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
