# Generated by Django 5.1.5 on 2025-01-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_daily_progress_userprofile_daily_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.company'),
        ),
    ]
