# Generated by Django 5.1.5 on 2025-01-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_yesterday_calls'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_work_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
