# Generated by Django 5.1.5 on 2025-01-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userprofile_session_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Sales Representative', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shift',
            field=models.CharField(default='9:00 AM - 5:00 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=10),
        ),
    ]
